name = "maninho-criativos-links"
compatibility_date = "2026-09-04"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "maninho-links-db"
database_id = "807715b6-58cd-4b3f-894d-1920ff97ff68"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "maninho-criativos-storage"
