import { errorResponse, HttpError, integer, json, readJson, text } from '../_utils.js';
import { requireAuth } from './_auth.js';

const STATUSES = new Set(['briefing','creation','review','approved','delivered','paused','cancelled']);
function values(body) {
  const status = text(body.status || 'briefing', { required:true, max:20 });
  if (!STATUSES.has(status)) throw new HttpError(400, 'Etapa inválida');
  const deadline = text(body.deadline, { max:10 });
  if (deadline && !/^\d{4}-\d{2}-\d{2}$/.test(deadline)) throw new HttpError(400, 'Prazo inválido');
  return { client_id:integer(body.client_id,{min:1}), title:text(body.title,{required:true,max:160}), service:text(body.service,{required:true,max:120}), status, value_cents:integer(body.value_cents,{min:0,max:100_000_000}), deadline:deadline||null, progress:integer(body.progress,{min:0,max:100}), notes:text(body.notes,{max:1000}) };
}
export async function onRequestGet({request,env}) { const denied=await requireAuth(request,env);if(denied)return denied;const {results}=await env.DB.prepare(`SELECT p.*,c.name client_name,c.email client_email FROM design_projects p JOIN clients c ON c.id=p.client_id ORDER BY CASE p.status WHEN 'review' THEN 1 WHEN 'creation' THEN 2 WHEN 'briefing' THEN 3 ELSE 4 END,p.deadline IS NULL,p.deadline,p.id DESC`).all();return json({projects:results||[]}); }
export async function onRequestPost({request,env}) { try{const denied=await requireAuth(request,env);if(denied)return denied;const p=values(await readJson(request));const client=await env.DB.prepare(`SELECT id FROM clients WHERE id=? AND is_active=1`).bind(p.client_id).first();if(!client)throw new HttpError(404,'Cliente não encontrado');const row=await env.DB.prepare(`INSERT INTO design_projects(client_id,title,service,status,value_cents,deadline,progress,notes) VALUES(?,?,?,?,?,?,?,?) RETURNING id`).bind(p.client_id,p.title,p.service,p.status,p.value_cents,p.deadline,p.progress,p.notes).first();await env.DB.prepare(`INSERT INTO crm_activities(entity_type,entity_id,action,details) VALUES('project',?,'created',?)`).bind(row.id,p.title).run();return json({id:row.id},201);}catch(e){return errorResponse(e);} }
export async function onRequestPut({request,env}) { try{const denied=await requireAuth(request,env);if(denied)return denied;const body=await readJson(request);const id=integer(body.id,{min:1});const p=values(body);const result=await env.DB.prepare(`UPDATE design_projects SET client_id=?,title=?,service=?,status=?,value_cents=?,deadline=?,progress=?,notes=?,updated_at=datetime('now') WHERE id=?`).bind(p.client_id,p.title,p.service,p.status,p.value_cents,p.deadline,p.progress,p.notes,id).run();if(!result.meta.changes)throw new HttpError(404,'Projeto não encontrado');return json({ok:true});}catch(e){return errorResponse(e);} }
export async function onRequestDelete({request,env}) { try{const denied=await requireAuth(request,env);if(denied)return denied;const id=integer(new URL(request.url).searchParams.get('id'),{min:1});await env.DB.prepare(`UPDATE design_projects SET status='cancelled',updated_at=datetime('now') WHERE id=?`).bind(id).run();return json({ok:true});}catch(e){return errorResponse(e);} }
